import Head from 'next/head';

const Home = () => {
    return (
        <>
            <Head>
                <title>TODO App Next.JS 13</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1>HI</h1>
            </main>
        </>
    )
};

export default Home;