"use client"
import { FC } from 'react';
import Head from 'next/head';

const Home: FC = () => {
    return (
        <>
            <Head>
                <title>Next 13 TODO Application!</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1>
                    TODO
                </h1>
            </main>
        </>
    )
};

export default Home;